---
name: App-ZofCMS-Plugin-Barcode
version: 0.0102
author:
  - "'Zoffix <'zoffix@cpan.org'>"
abstract: plugin to generate various bar codes
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
requires:
  App::ZofCMS::Plugin::Base: 0.0103
  GD::Barcode: 1.15
configure_requires:
  Module::Build: 0.34
provides:
  App::ZofCMS::Plugin::Barcode:
    file: lib/App/ZofCMS/Plugin/Barcode.pm
    version: 0.0102
generated_by: Module::Build version 0.34
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
